### ISSUE TITLE
geometryUrl error

### ISSUE THREAD

**Issue by tiwaab-zz** [stevage/mapbox-choropleth#1]
Hi @stevage not sure if this is the right forum for this but I'm a novice data analyst who used your library to create a choropleth of popular DC neighbourhoods according to Airbnb. I've copied every line of code as it appears in the example but I keep getting the following errors
`Error: sources.choropleth: unknown property "url" `
`Error: layers.choropleth: source "choropleth" not found`
`Error: layers.choropleth.source-layer: string expected, undefined found`
but when I run `console.log(c.geometryUrl)` it shows me the correct url. Any idea why I'm getting this error? 😫 Sorry again if this isn't the right place/format to ask for help.

This is my HTML code:

`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Popular DC Neigbourhoods on Airbnb</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />
  <script src="https://unpkg.com/mapbox-choropleth"></script>
  <style>
   body {
        margin: 0;
        padding: 0;
      }

      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
  </style>
</head>

<body>
  
  <div id='map'></div>
  <script>

mapboxgl.accessToken = 'pk.eyJ1IjoidGJydWtzIiwiYSI6ImNqZDdrcG5ucDJsbG8yem53emR4aHBmMjQifQ.1BRqWpJKeGPKtvwCq5Qqyw';

var map = new mapboxgl.Map({
  container: 'map', //container id
  style: 'mapbox://styles/mapbox/dark-v9', // stylesheet url
  center: [-77.036904, 38.915509], //starting position
  zoom: 11 //starting zoom
});

let c = new MapboxChoropleth({ 
    tableUrl: 'Resources/cleaned_reviews.csv',
    tableNumericField: 'number_of_reviews',
    tableIdField: 'neighbourhood',
    geometryIdField: 'neighbourhood',
    geometryUrl: 'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-10-12/visualisations/neighbourhoods.geojson',
    binCount: 7,
    colorScheme: 'Spectral',
    // legendElement: '#legend'
 }).addTo(map);
  </script>
</body>
</html>`

**Comment by stevage** [comment]
Thanks for getting in touch. Looks like I didn't properly test geojson geometries. I've updated the code and pushed version 0.7.4.

I couldn't quite test your example code as I don't have the CSVs. Hopefully it works now though.

**Comment by tiwaab-zz** [comment]
Awesome, it works now! Thank you
