### ISSUE TITLE
Labels on top

### ISSUE THREAD

**Issue by tiwaab-zz** [stevage/mapbox-choropleth#2]
Is there a way to move labels to the top so they aren't obstructed by the choropleth? Mapbox's [method](https://www.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/) doesn't work with this plugin

**Comment by stevage** [comment]
Sorry, just saw this. You closed this because you found a way?

**Comment by tiwaab-zz** [comment]
Hi Steve, I decided that the choropleth actually looked better without the labels. Thanks for checking in.
